### ISSUE TITLE
Error when activating

### ISSUE THREAD

**Issue by spiderflystudios** [jonathan-dejong/acf-form-shortcode#1]
Showed up twice exactly as below when activating.  Using the most recent version of WordPress.  ACF Pro is up to date as well.

Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'Acf_Form_Shortcode_Admin' does not have a method 'enqueue_styles' in /home/content/21/3843821/html/wp-includes/plugin.php on line 525

Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'Acf_Form_Shortcode_Admin' does not have a method 'enqueue_scripts' in /home/content/21/3843821/html/wp-includes/plugin.php on line 525

**Comment by jonathan-dejong** [comment]
Will fix promptly!

I threw this up a bit hastily :D
