### ISSUE TITLE
Notice when outside the loop

### ISSUE THREAD

**Issue by jeremyhalin** [jonathan-dejong/acf-form-shortcode#3]
Hi,

I have an error on my wordpress site when I'm outside the loop and `$post` is `NULL`.

Here is the error:
`Notice: Trying to get property of non-object in wp-content/plugins/acf-form-shortcode-master/public/class-acf-form-shortcode-public.php`

Here is the code:
```php
public function enqueue_acf_form(){

	if( is_admin() )
		return;

	global $post;

	if( has_shortcode( $post->post_content, 'show_acf_form' ) ){
		acf_form_head();
	}

}
```

I'm using BuddyPress and this error occurs when on profile member page, thats why `$post` is `NULL`.

I suggest we need to do a check on `$post` value like so:
```php
public function enqueue_acf_form(){

	if( is_admin() )
		return;

	global $post;

	if( $post != NULL && has_shortcode( $post->post_content, 'show_acf_form' ) ){
		acf_form_head();
	}

}
```

**Comment by jonathan-dejong** [comment]
Hi @HJerem 

Ah Yeah that should be fixed.
I think however a better solution would be  to add ! is_singular() to the existing if statement.
